# SPDX-License-Identifier: GPL-2.0-or-later
obj-$(CONFIG_RTD129X_ACPU) += rtd129x-acpu.o
rtd129x-acpu-y := acpu-rpc.o

obj-$(CONFIG_SND_RTD129X_HDMIRX) += snd-rtd129x-hdmirx.o
snd-rtd129x-hdmirx-y := acpu-pcm.o

obj-$(CONFIG_RTD129X_VO) += rtd129x-vo.o
rtd129x-vo-y := acpu-vo.o acpu-dp.o
